-- V2 Fase 1: Multi-tenant entities
-- Generated by: prisma migrate diff --from-schema (pre-v2) --to-schema (v2)
-- Da applicare via: psql o prisma db execute

-- CreateEnum
CREATE TYPE "fin_user_type" AS ENUM ('CONTROLLER', 'CLIENT_OWNER', 'CLIENT_ADMIN_BANK_ONLY');

-- CreateEnum
CREATE TYPE "fin_cdg_granularity" AS ENUM ('MONTHLY', 'QUARTERLY');

-- AlterTable
ALTER TABLE "fin_organization" ADD COLUMN     "accounting_firm_id" TEXT,
ADD COLUMN     "cdg_granularity" "fin_cdg_granularity" DEFAULT 'MONTHLY',
ADD COLUMN     "client_group_id" TEXT;

-- AlterTable
ALTER TABLE "fin_user" ADD COLUMN     "accounting_firm_id" TEXT,
ADD COLUMN     "user_type" "fin_user_type";

-- CreateTable
CREATE TABLE "finflow"."accounting_firm" (
    "id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "vat_number" TEXT,
    "email" TEXT,
    "phone" TEXT,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "accounting_firm_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "finflow"."client_group" (
    "id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "accounting_firm_id" TEXT NOT NULL,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "client_group_pkey" PRIMARY KEY ("id")
);

-- AddForeignKey
ALTER TABLE "finflow"."client_group" ADD CONSTRAINT "client_group_accounting_firm_id_fkey" FOREIGN KEY ("accounting_firm_id") REFERENCES "finflow"."accounting_firm"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "fin_organization" ADD CONSTRAINT "fin_organization_accounting_firm_id_fkey" FOREIGN KEY ("accounting_firm_id") REFERENCES "finflow"."accounting_firm"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "fin_organization" ADD CONSTRAINT "fin_organization_client_group_id_fkey" FOREIGN KEY ("client_group_id") REFERENCES "finflow"."client_group"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "fin_user" ADD CONSTRAINT "fin_user_accounting_firm_id_fkey" FOREIGN KEY ("accounting_firm_id") REFERENCES "finflow"."accounting_firm"("id") ON DELETE SET NULL ON UPDATE CASCADE;
